<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <?php if (isset($_GET['error']) && $_GET['error'] == 'str_length') { ?>
          <div class="bg-danger text-white rounded p-3 m-3">
            Os campos tem menos que 3 caracteres.
          </div>
        <?php } else if (isset($_GET['error']) && $_GET['error'] == 'email_found') { ?>
          <div class="bg-danger text-white rounded p-3 m-3">
            Este e-mail já existe, utilize outro.
          </div>
        <?php } ?>

        <div class="row">
          <div class="col">
            
            <form action="/register" method="post">
              <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input type="email" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  